#
# Makefile for all kinds of Fingerprint
#
# obj-$(CONFIG_FPC_FINGERPRINT) +=  fpsensor_ree/
#obj-$(CONFIG_FPC_FINGERPRINT) +=  fpsensor_tee/
# obj-y +=  focaltech_ree/
obj-$(CONFIG_FPC_FINGERPRINT) +=  fpsensor_tee/
obj-$(CONFIG_FOCAL_FINGERPRINT) +=  focaltech_tee/
